kind: pipeline
type: docker
name: deploy

steps:
  - name: ansible-deploy
    image: cytopia/ansible:latest
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "false"
    commands:
      - ansible --version
      - echo "Pipeline triggered successfully"

trigger:
  branch:
    - main
  event:
    - push
