---
- name: Apply common configuration to all nodes
  hosts: cluster_nodes
  become: true
  roles:
    - common
    - pacemaker
    - monitoring
    - logging
    - alertmanager
    - drbd
    - gitea
